version: '2'
services:
  db:
    image: postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data
  project:
    build: .
    image: project:latests
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres
      - DEBUG=True
volumes:
  pgdata:
